version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: itattoo
      POSTGRES_USER: itattoo
      POSTGRES_PASSWORD: "itattoo2022"
    ports:
      - "5432:5432"
    volumes:
      - /home/jadsonsanches/www/jadson/itattoo/docker-compose/postgreSQL:/var/lib/postgresql/data
